name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AKSHITA_SECRET }}

    - name: Deploy to VM
      run: |
        # Adding the SSH key to the SSH agent
        echo "${{ secrets.AKSHITA_SECRET }}" > /tmp/AKSHITA-VMM_key.pem
        chmod 600 /tmp/AKSHITA-VMM_key.pem
        eval "$(ssh-agent -s)"
        ssh-add /tmp/AKSHITA-VMM_key.pem

        # SSH into the Azure VM and deploy
        ssh -o StrictHostKeyChecking=no -i /tmp/AKSHITA-VMM_key.pem userazure@20.221.72.59 << 'EOF'
          cd ~/flask-hello-world
          git pull origin master
          sudo systemctl restart flask-hello-world
        EOF
